# aeutil
# Autogenerated from man page /usr/share/man/man1/aeutil.1
# using Darwin man parser
complete -c aeutil -s a --description 'Description of -a flag.'
complete -c aeutil -s b --description 'Description of -b flag \\" Ends the list Pp .'

