# axel
# Autogenerated from man page /usr/local/share/man/man1/axel.1
# using Deroffing man parser
complete -c axel -l max-speed -o sx --description 'You can specify a speed (bytes per second) here… [See Man Page]'
complete -c axel -l num-connections -o nx --description 'You can specify an alternative number of connections here.'
complete -c axel -l output -o ox --description 'Downloaded data will be put in a local file wit… [See Man Page]'
complete -c axel -l 'search[' -o 'S[x]' --description 'Axel can do a search for mirrors using the filesearching.'
complete -c axel -l no-proxy -s N --description 'Don\'t use any proxy server to download the file.'
complete -c axel -l verbose --description 'If you want to see more status messages, you ca… [See Man Page]'
complete -c axel -l quiet -s q --description 'No output to stdout.'
complete -c axel -l alternate -s a --description 'This will show an alternate progress indicator.'
complete -c axel -l header -o Hx --description 'Add an additional HTTP header.'
complete -c axel -l user-agent -o Ux --description 'Set the HTTP user agent to use.'
complete -c axel -l help -s h --description 'A brief summary of all the options.'
complete -c axel -s s --description 'You can specify a speed (bytes per second) here… [See Man Page]'
complete -c axel -s n --description 'You can specify an alternative number of connections here.'
complete -c axel -s o --description 'Downloaded data will be put in a local file wit… [See Man Page]'
complete -c axel -s H --description 'Add an additional HTTP header.'
complete -c axel -s U --description 'Set the HTTP user agent to use.'
complete -c axel -l version -s V --description 'Get version information.'

