# brew-man
# Autogenerated from man page /usr/local/share/man/man1/brew-man.1
# using Type1
complete -c brew-man -s v -l verbose --description 'Run man brew after generating man pages.'
complete -c brew-man -s l -l link --description 'Creates symlinks from the generated man pages t… [See Man Page]'

