# ccrewrite
# Autogenerated from man page /usr/share/man/man1/ccrewrite.1
# using Deroffing man parser
complete -c ccrewrite -l assembly --description 'The assembly to rewrite.'
complete -c ccrewrite -l debug --description 'Use debug information if available to improve t… [See Man Page]'
complete -c ccrewrite -l help --description 'Show help for ccrewrite, listing configuration options.'
complete -c ccrewrite -l level --description 'Set the which contract types are present in rew… [See Man Page]'
complete -c ccrewrite -l output --description 'Write the rewritten assembly to the specified file.'
complete -c ccrewrite -l rewrite --description 'Rewrite the assembly.  If false, then nothing is done.'
complete -c ccrewrite -l throwOnFailure --description 'Throw a ContractException on unhandled contract failure.'

