# certmgr
# Autogenerated from man page /usr/share/man/man1/certmgr.1
# using Deroffing man parser
complete -c certmgr -s m --description 'Use the machine\'s certificate stores (instead o… [See Man Page]'
complete -c certmgr -s v --description 'More details displayed on the console.'
complete -c certmgr -s p --description 'Use the specify password when accessing a pkcs12 file.'
complete -c certmgr -o list --description 'List the certificates, CTL or CTL in the specified store.'
complete -c certmgr -o add --description 'Add a certificate, CRL or CTL to specified store.'
complete -c certmgr -o del --description 'Remove a certificate, CRL or CTL from specified store.'
complete -c certmgr -o put --description 'Copy a certificate, CRL or CTL from a store to a file.'
complete -c certmgr -o ssl --description 'Download and add the certificates from a SSL session.'
complete -c certmgr -o importKey --description 'Allows importing a private key from a pkcs12 fi… [See Man Page]'
complete -c certmgr -s c -o cert -o certificate --description 'Add, Delete or Put certificates.'
complete -c certmgr -o crl --description 'Add, Delete or Put certificate revocation lists (CRL).'
complete -c certmgr -o ctl --description 'Add, Delete or Put certificate trust lists (CRL).  UNSUPPORTED.'
complete -c certmgr -o help -s h -s '?' --description 'Display help about this tool.'

