# chktrust
# Autogenerated from man page /usr/share/man/man1/chktrust.1
# using Deroffing man parser
complete -c chktrust -s q -o quiet --description 'Quiet mode.  Limited display on console.'
complete -c chktrust -s v -o verbose --description 'Verbose mode.  More details displayed on the console.'
complete -c chktrust -o help -s h -s '?' --description 'Display help about this tool.'

