# csharp
# Autogenerated from man page /usr/share/man/man1/csharp.1
# using Deroffing man parser
complete -c csharp -l attach --description 'This is an advanced option and should only be u… [See Man Page]'
complete -c csharp -s e --description 'This will evaluate the specified C# EXPRESSION … [See Man Page]'

