# cutmp3
# Autogenerated from man page /usr/share/man/man1/cutmp3.1.gz
# using Deroffing man parser
complete -c cutmp3 -s i --description 'input file to edit.'
complete -c cutmp3 -s O --description 'forced output filename.'
complete -c cutmp3 -s o --description 'prefix of generated output filename . br (e. g.'
complete -c cutmp3 -s a --description 'starting position of selection to write to new file.'
complete -c cutmp3 -s b --description 'end position of selection to write to new file.'
complete -c cutmp3 -s f --description 'use a timetable to extract several sequences from a given file.'
complete -c cutmp3 -s e --description 'Switch on exact searching mode, useful for VBR files.'
complete -c cutmp3 -s q --description 'Switch on quiet mode, cutmp3 won\'t make any sou… [See Man Page]'
complete -c cutmp3 -s c --description 'Copies metadata in non-interactive mode.'
complete -c cutmp3 -s s --description 'Normally cutmp3 stops when the silence found is… [See Man Page]'
complete -c cutmp3 -s d --description 'use the second soundcard (/dev/dsp1).'

