# dbsessmgr
# Autogenerated from man page /usr/share/man/man1/dbsessmgr.1.gz
# using Deroffing man parser
complete -c dbsessmgr -l clean --description 'Remove all expired sessions.'
complete -c dbsessmgr -l remove --description 'Delete all sessions.'
complete -c dbsessmgr -l show --description 'Display session data.'

