# diameter_compile
# Autogenerated from man page /usr/local/share/man/man1/diameter_compile.1
# using Deroffing man parser
complete -c diameter_compile -s o --description 'Specifies the directory into which the generate… [See Man Page]'
complete -c diameter_compile -s i --description 'Specifies a directory to add to the code path.'
complete -c diameter_compile -o E: --description 'Supresses erl generation.'
complete -c diameter_compile -o H: --description 'Supresses hrl generation.'
complete -c diameter_compile -l name --description 'Set @name in the dictionary file.'
complete -c diameter_compile -l prefix --description 'Set @prefix in the dictionary file.'
complete -c diameter_compile -l inherits --description 'Append an @inherits to the dictionary file.'

