# disco
# Autogenerated from man page /usr/share/man/man1/disco.1
# using Deroffing man parser
complete -c disco -o nologo --description 'Supress the startup logo.'
complete -c disco -o nosave --description 'Do not save the discovered documents to disk.'
complete -c disco -o o:directory -o out:directory --description 'The directory where to save the discovered documents.'
complete -c disco -o u:username -o user:username --description 'The user name to use when connecting to the server.'
complete -c disco -o p:password -o password:password --description 'The password to use when connecting to the server.'
complete -c disco -o d:domain -o domain:domain --description 'The domain to use when connecting to the server.'
complete -c disco -o proxy:url --description 'The url of the proxy server to use for http requests.'
complete -c disco -o proxyusername:username --description 'The user name to use when connecting to the proxy.'
complete -c disco -o proxypassword:password --description 'The password to use when connecting to the proxy.'
complete -c disco -o proxydomain:domain --description 'The domain to use when connecting to the proxy.'

