# httpcfg
# Autogenerated from man page /usr/share/man/man1/httpcfg.1
# using Deroffing man parser
complete -c httpcfg -o add --description 'Adds a new certificate/private key combination … [See Man Page]'
complete -c httpcfg -o del -o delete --description 'Deletes the certificates associated for the por… [See Man Page]'
complete -c httpcfg -o list --description 'List all known certificates.'
complete -c httpcfg -o port --description 'Specifies the port to add certificates to, or r… [See Man Page]'
complete -c httpcfg -o pvk --description 'Specifies the Private Key file.'
complete -c httpcfg -o cert --description 'Specifies the certificate file to use.  EXAMPLES.'

