# ilasm
# Autogenerated from man page /usr/share/man/man1/ilasm.1
# using Deroffing man parser
complete -c ilasm -l about --description 'Display information about ilasm.'
complete -c ilasm -l version --description 'Display ilasm version SEE ALSO mono(1), mcs(1) … [See Man Page]'

