# lc
# Autogenerated from man page /usr/share/man/man1/lc.1
# using Deroffing man parser
complete -c lc -l complist -s c --description 'This option is used to specify the input file, the licenses.'
complete -c lc -l target -s t --description 'full assembly name with file extension for the target assembly.'
complete -c lc -l load -s i --description 'Assembly reference to load before trying to compile a license.'
complete -c lc -l verbose -s v --description 'Gives more verbose output about the license compiling process.'
complete -c lc -l help -s h --description 'Displays usage instructions.'
complete -c lc -l outdir -s o --description 'Target path file the licenses resource.'
complete -c lc -l nologo --description 'Do not emit the "Mono License Compiler" logo  o… [See Man Page]'

