# macpack
# Autogenerated from man page /usr/share/man/man1/macpack.1
# using Deroffing man parser
complete -c macpack -o mode: --description 'libraries is setup.'
complete -c macpack -s a --description '.'
complete -c macpack -s m --description 'or.'
complete -c macpack -o 'mode:[winforms' --description '.'
complete -c macpack -s n --description 'or.'
complete -c macpack -o appname:NAME --description '.'
complete -c macpack -s o --description 'or.'
complete -c macpack -o output:DIRECTORY --description '.'
complete -c macpack -s r --description 'or .'
complete -c macpack -o resource:RESOURCE --description '.'

