# mautil
# Autogenerated from man page /usr/share/man/man1/mautil.1
# using Deroffing man parser
complete -c mautil -l registry -o reg --description 'Specify add-in registry path.'
complete -c mautil -l path -s p --description 'Specify startup path.'
complete -c mautil -s v --description 'Verbose output . SS "Add-in commands:".'

