# mconfig
# Autogenerated from man page /usr/share/man/man1/mconfig.1
# using Deroffing man parser
complete -c mconfig -s c -l config --description 'Read the specified config file after reading th… [See Man Page]'
complete -c mconfig -s t -l target --description 'Features and default configuration files define… [See Man Page]'
complete -c mconfig -s '?' -s h -l help --description 'Show a summary usage screen.'
complete -c mconfig -s v -l version --description 'Show the mconfig version COMMANDS.'

