# mdoc-update
# Autogenerated from man page /usr/share/man/man1/mdoc-update.1
# using Deroffing man parser
complete -c mdoc-update -l delete --description 'Allow mdoc update to delete members from documentation files.'
complete -c mdoc-update -l 'exceptions[' --description 'EXPERIMENTAL.'
complete -c mdoc-update -s f --description 'Specify a flag to alter behavior.   Valid flags include: . RS .'
complete -c mdoc-update -o fno-assembly-versions --description 'Do not generate /Type/AssemblyInfo/AssemblyVers… [See Man Page]'
complete -c mdoc-update -s i -l import --description 'Import documentation found within FILE.'
complete -c mdoc-update -s L -l lib --description 'Add DIRECTORY to the assembly search path, so t… [See Man Page]'
complete -c mdoc-update -s o -l out --description 'Place the generated stubs into DIRECTORY.'
complete -c mdoc-update -s r --description 'ASSEMBLY is a dependency for one of ASSEMBLIES … [See Man Page]'
complete -c mdoc-update -l since --description 'When updating documentation for an assembly, if… [See Man Page]'
complete -c mdoc-update -l type --description 'Only update documentation for the type TYPE.'
complete -c mdoc-update -s h -s '?' -l help --description 'Display a help message and exit.'

