# mdoc-validate
# Autogenerated from man page /usr/share/man/man1/mdoc-validate.1
# using Deroffing man parser
complete -c mdoc-validate -l format --description 'The documentation format to validate PATHS against.'
complete -c mdoc-validate -s h -s '?' -l help --description 'Display a help message and exit.'

