# mdoc-assemble
# Autogenerated from man page /usr/share/man/man1/mdoc-assemble.1
# using Deroffing man parser
complete -c mdoc-assemble -s f -l format --description 'Specifies the documentation format used within PATHS.'
complete -c mdoc-assemble -s o -l out --description 'Specify the output file prefix.'
complete -c mdoc-assemble -s h -s '?' -l help --description 'Display a help message and exit.'

