# mdoc-export-html
# Autogenerated from man page /usr/share/man/man1/mdoc-export-html.1
# using Deroffing man parser
complete -c mdoc-export-html -l default-template --description 'Writes the default XSLT used to stdout.'
complete -c mdoc-export-html -l ext --description 'The file extension to use for created files.'
complete -c mdoc-export-html -l force-update --description 'Always generate new files.'
complete -c mdoc-export-html -s o -l out --description 'Write the created files within directory DIRECTORY.'
complete -c mdoc-export-html -l template --description 'An XSLT file to use to generate the created files.'
complete -c mdoc-export-html -l with-profile --description 'Only process types and members within the .'
complete -c mdoc-export-html -l with-version --description 'Only process types and members within the assem… [See Man Page]'
complete -c mdoc-export-html -s h -s '?' -l help --description 'Display a help message and exit.'

