# mkbundle
# Autogenerated from man page /usr/share/man/man1/mkbundle.1
# using Deroffing man parser
complete -c mkbundle -s c --description 'Produce the stub file, do not compile the resulting stub.'
complete -c mkbundle -s o --description 'Places the output on `out\'.'
complete -c mkbundle -o oo --description 'Specifies the name to be used for the helper ob… [See Man Page]'
complete -c mkbundle -s L --description 'Adds the `path\' do the search list for assemblies.'
complete -c mkbundle -l config --description 'Specifies that a machine. config file must be bundled as well.'
complete -c mkbundle -l nodeps --description 'This is the default: mkbundle will only include… [See Man Page]'
complete -c mkbundle -l deps --description 'This option will bundle all of the referenced a… [See Man Page]'
complete -c mkbundle -l keeptemp --description 'By default mkbundle will delete the temporary f… [See Man Page]'
complete -c mkbundle -l machine-config --description 'Uses the given FILE as the machine.'
complete -c mkbundle -l nomain --description 'With the -c option, generate the host stub with… [See Man Page]'
complete -c mkbundle -l config-dir --description 'When passed, DIR will be set for the MONO_CFG_D… [See Man Page]'
complete -c mkbundle -l static --description 'By default mkbundle dynamically links to mono and glib.'
complete -c mkbundle -s z --description 'Compresses the assemblies before embedding.'

