# mono-xmltool
# Autogenerated from man page /usr/share/man/man1/mono-xmltool.1
# using Deroffing man parser
complete -c mono-xmltool -l validate-xxx --description '.'
complete -c mono-xmltool -l validate-rng --description '.'
complete -c mono-xmltool -l validate-rnc --description 'Commons. Xml. Relaxng. RncParser as the schema, and Commons.'
complete -c mono-xmltool -l validate-nvdl --description '.'
complete -c mono-xmltool -l validate-xsd --description 'System. Xml. Schema. XmlSchema as the schema and uses System.'

