# mono-shlib-cop
# Autogenerated from man page /usr/share/man/man1/mono-shlib-cop.1
# using Deroffing man parser
complete -c mono-shlib-cop -s p -l prefixes --description 'Mono installation prefixes.'
complete -c mono-shlib-cop -o devel --description 'packages which provide the  unversioned library.'

