# mono-api-info
# Autogenerated from man page /usr/share/man/man1/mono-api-info.1
# using Deroffing man parser
complete -c mono-api-info -l abi --description 'Show the ABI instead of the API, that is, non-s… [See Man Page]'

