# monodocs2html
# Autogenerated from man page /usr/share/man/man1/monodocs2html.1
# using Deroffing man parser
complete -c monodocs2html -o dest:DEST_DIR --description 'Write the HTML files into the directory  DEST_DIR .'
complete -c monodocs2html -o dumptemplate --description 'Dump the default page template to standard outp… [See Man Page]'
complete -c monodocs2html -o ext:FILE_EXTENSION --description 'FILE_EXTENSION is the file extension for generated files.'
complete -c monodocs2html -s '?' -o help --description 'Show program argument information.'
complete -c monodocs2html -o onlytype:TYPE --description 'Only generate HTML for the type  TYPE .'
complete -c monodocs2html -o source:SOURCE_DIR --description 'SOURCE_DIR is the base directory containing the… [See Man Page]'
complete -c monodocs2html -o template:TEMPLATE --description 'Generate HTML using the page template  TEMPLATE .'
complete -c monodocs2html -o template --description 'option.'
complete -c monodocs2html -s V -o version --description 'Display version and licensing information.'

