# monodocer
# Autogenerated from man page /usr/share/man/man1/monodocer.1
# using Deroffing man parser
complete -c monodocer -o assembly:ASSEMBLY --description 'ASSEMBLY is a .'
complete -c monodocer -o delete --description 'Allow monodocer to delete members from documentation files.'
complete -c monodocer -s '?' -o help --description 'Show program argument information.'
complete -c monodocer -o ignoremembers --description 'Do not update members.'
complete -c monodocer -o importslashdoc:FILE --description 'FILE is an XML file generated with the   /doc:F… [See Man Page]'
complete -c monodocer -o name:NAME --description 'NAME is the name of the project this documentation is for.'
complete -c monodocer -o namespace:NAMESPACE --description 'Only update the types within the namespace  NAMESPACE .'
complete -c monodocer -o overrides --description 'Include overridden methods in documentation.'
complete -c monodocer -o path:OUTPUT_DIR --description 'OUTPUT_DIR is the directory which will contain … [See Man Page]'
complete -c monodocer -o pretty --description 'Indent the XML files nicely.'
complete -c monodocer -o since:SINCE --description 'Create a <since/> element for added types and m… [See Man Page]'
complete -c monodocer -o type:TYPE --description 'Only create/update documentation for the type  TYPE .'
complete -c monodocer -o updateto:PATH --description 'When updating documentation, write the updated … [See Man Page]'
complete -c monodocer -o path --description ' This is used by some programs for title information (e. g.'
complete -c monodocer -o since: --description 'an element will be inserted into the  Docs elem… [See Man Page]'
complete -c monodocer -s V -o version --description 'Display version and licensing information.'

