# mono-service
# Autogenerated from man page /usr/share/man/man1/mono-service.1
# using Deroffing man parser
complete -c mono-service -o d:DIRECTORY --description 'Use this option to specify the working director… [See Man Page]'
complete -c mono-service -o l:LOCKFILE --description 'Specifies the file to use for locking, the defa… [See Man Page]'
complete -c mono-service -o m:MESSAGE --description 'Name to show in the syslog.'
complete -c mono-service -o n:NAME --description 'Use this to specify the service to be launched … [See Man Page]'
complete -c mono-service -l debug --description 'Use this option to prevent mono-service from re… [See Man Page]'
complete -c mono-service -l no-daemon --description 'Use this option to prevent mono-service from re… [See Man Page]'

