# mozroots
# Autogenerated from man page /usr/share/man/man1/mozroots.1
# using Deroffing man parser
complete -c mozroots -l import --description 'Import the certificates into the trust store.'
complete -c mozroots -l sync --description 'Synchronize (add/remove) the trust store with the certificates.'
complete -c mozroots -l ask --description 'Always confirm before adding or removing trusted certificates.'
complete -c mozroots -l ask-add --description 'Always confirm before adding a new trusted certificate.'
complete -c mozroots -l ask-remove --description 'Always confirm before removing an existing trusted certificate.'
complete -c mozroots -l url --description 'Specify an alternative URL for downloading the … [See Man Page]'
complete -c mozroots -l file --description 'Do not download from LXR but use the specified file.'
complete -c mozroots -l pkcs7 --description 'Export the certificates into a PKCS#7 file.'
complete -c mozroots -l machine --description 'Import the certificate in the machine trust store.'
complete -c mozroots -l quiet --description 'Limit console output to errors and confirmations messages.'

