# msdl
# Autogenerated from man page /usr/local/share/man/man1/msdl.1
# using Type1
complete -c msdl -s o -l output --description 'specify output file name.'
complete -c msdl -s l -l logfile --description 'print log to logfile instead of console.'
complete -c msdl -s v -l verbose --description 'show verbose messages.'
complete -c msdl -s V -l version --description 'show version information.'
complete -c msdl -s q -l quiet --description 'do quietly.  no output.'
complete -c msdl -s c -l continue --description 'continue downloading url.'
complete -c msdl -s a -l auto-retry --description 'auto-retry aborted download, <num> times.'
complete -c msdl -s b -l bandwidth --description 'set bandwidth.'
complete -c msdl -s s -l speed --description 'nf set streaming speed.  default is "1. 000".'
complete -c msdl -s r -l range --description 'nf set range (for RTSP).  default is "0. 000-".'
complete -c msdl -s m -l metafile --description 'treat url as metafile.'
complete -c msdl -s n -l no-metafile --description 'DO NOT treat url as metafile.'
complete -c msdl -s h -l help --description 'display help message.'
complete -c msdl -s p -l protocol --description 'specify download protocol.'
complete -c msdl -l byterange --description 'specify byterange to get.'
complete -c msdl -l username --description 'user name for http and ftp.'
complete -c msdl -l password --description 'password for http and ftp.'
complete -c msdl -l no-proxy --description 'DO NOT use proxy, even if HTTP_PROXY set.'
complete -c msdl -l no-passive-ftp --description 'DO NOT use passive mode in FTP.'
complete -c msdl -l stream-timeout --description 'nf Quit streaming after specified time (second).'

