# pdffonts
# Autogenerated from man page /usr/local/share/man/man1/pdffonts.1
# using Deroffing man parser
complete -c pdffonts -s f --description 'Specifies the first page to analyze.'
complete -c pdffonts -s l --description 'Specifies the last page to analyze.'
complete -c pdffonts -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdffonts -o upw --description 'Specify the user password for the PDF file.'
complete -c pdffonts -o cfg --description 'Read  config-file in place of ~/.'
complete -c pdffonts -s v --description 'Print copyright and version information.'
complete -c pdffonts -s h --description 'Print usage information.  ( -help and.'
complete -c pdffonts -l help --description 'are equivalent.'

