# pdftotext
# Autogenerated from man page /usr/local/share/man/man1/pdftotext.1
# using Deroffing man parser
complete -c pdftotext -s f --description 'Specifies the first page to convert.'
complete -c pdftotext -s l --description 'Specifies the last page to convert.'
complete -c pdftotext -o layout --description 'Maintain (as best as possible) the original phy… [See Man Page]'
complete -c pdftotext -o raw --description 'Keep the text in content stream order.'
complete -c pdftotext -o htmlmeta --description 'Generate a simple HTML file, including the meta information.'
complete -c pdftotext -o enc --description 'Sets the encoding to use for text output.'
complete -c pdftotext -o eol --description 'Sets the end-of-line convention to use for text output.'
complete -c pdftotext -o nopgbrk --description 'Don\'t insert page breaks (form feed characters) between pages.'
complete -c pdftotext -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdftotext -o upw --description 'Specify the user password for the PDF file.'
complete -c pdftotext -s q --description 'Don\'t print any messages or errors.'
complete -c pdftotext -o cfg --description 'Read  config-file in place of ~/.'
complete -c pdftotext -s v --description 'Print copyright and version information.'
complete -c pdftotext -s h --description 'Print usage information.  ( -help and.'
complete -c pdftotext -l help --description 'are equivalent. ).'

