# permview
# Autogenerated from man page /usr/share/man/man1/permview.1
# using Deroffing man parser
complete -c permview -o output --description 'Output all declarative security attributes rela… [See Man Page]'
complete -c permview -o xml -l xml --description 'Output all declarative security attributes in an XML format.'
complete -c permview -o decl -l decl --description 'Show declarative security attributes on classes and methods.'
complete -c permview -s '?' -o 'h[elp]' --description 'Display help informations about the permview tool.'

