# pgrep
# Autogenerated from man page /usr/share/man/man1/pgrep.1
# using Darwin man parser
complete -c pgrep -s F --description 'Restrict matches to a process whose PID is stor… [See Man Page]'
complete -c pgrep -s I --description 'Request confirmation before attempting to signal each process.'
complete -c pgrep -s a --description 'Include process ancestors in the match list.'
complete -c pgrep -s o --description 'Select only the oldest (least recently started)… [See Man Page]'
complete -c pgrep -s q --description 'Do not write anything to standard output.'
complete -c pgrep -o signal --description 'A non-negative decimal number or symbolic signa… [See Man Page]'

