# pkill
# Autogenerated from man page /usr/share/man/man1/pkill.1
# using Darwin man parser
complete -c pkill -s F --description 'Restrict matches to a process whose PID is stor… [See Man Page]'
complete -c pkill -s I --description 'Request confirmation before attempting to signal each process.'
complete -c pkill -s L --description 'The pidfile file given for the F option must be… [See Man Page]'
complete -c pkill -s d --description 'Specify a delimiter to be printed between each process ID.'
complete -c pkill -s a --description 'Include process ancestors in the match list.'
complete -c pkill -s o --description 'Select only the oldest (least recently started)… [See Man Page]'
complete -c pkill -s q --description 'Do not write anything to standard output.'

