# prj2make
# Autogenerated from man page /usr/share/man/man1/prj2make.1
# using Deroffing man parser
complete -c prj2make -s c -o isCsc --description 'Use csc instead of mcs on the generated files.'
complete -c prj2make -o csproj2prjx --description 'Runs in conversion mode, and turns a csproj/sln… [See Man Page]'
complete -c prj2make -s n -o isNmake --description 'Produce makefiles suitable to be used by Nmake.'

