# pscp
# Autogenerated from man page /usr/local/share/man/man1/pscp.1
# using Type1
complete -c pscp -s V --description 'Show version information and exit.'
complete -c pscp -o pgpfp --description 'Display the fingerprints of the PuTTY PGP Maste… [See Man Page]'
complete -c pscp -o ls --description 'Remote directory listing.'
complete -c pscp -s p --description 'Preserve file attributes.'
complete -c pscp -s q --description 'Quiet, don\'t show statistics.'
complete -c pscp -s r --description 'Copy directories recursively.'
complete -c pscp -o unsafe --description 'Allow server-side wildcards (DANGEROUS).'
complete -c pscp -s v --description 'Show verbose messages.'
complete -c pscp -o load --description 'Load settings from saved session.'
complete -c pscp -s P --description 'Connect to port port.'
complete -c pscp -s l --description 'Set remote username to user.'
complete -c pscp -o batch --description 'Disable interactive prompts.'
complete -c pscp -o pw --description 'Set remote password to password.'
complete -c pscp -s 1 --description 'Force use of SSH protocol version 1.'
complete -c pscp -s 2 --description 'Force use of SSH protocol version 2.'
complete -c pscp -s C --description 'Enable SSH compression.'
complete -c pscp -s i --description 'Private key file for authentication.'
complete -c pscp -o scp --description 'Force use of SCP protocol.'

