# psftp
# Autogenerated from man page /usr/local/share/man/man1/psftp.1
# using Type1
complete -c psftp -s V --description 'Show version information and exit.'
complete -c psftp -o pgpfp --description 'Display the fingerprints of the PuTTY PGP Maste… [See Man Page]'
complete -c psftp -s b --description 'Use specified batchfile.'
complete -c psftp -o bc --description 'Output batchfile commands.'
complete -c psftp -o be --description 'Don\'t stop batchfile processing on errors.'
complete -c psftp -s v --description 'Show verbose messages.'
complete -c psftp -o load --description 'Load settings from saved session.'
complete -c psftp -s P --description 'Connect to port port.'
complete -c psftp -s l --description 'Set remote username to user.'
complete -c psftp -o batch --description 'Disable interactive prompts.'
complete -c psftp -o pw --description 'Set remote password to password.'
complete -c psftp -s 1 --description 'Force use of SSH protocol version 1.'
complete -c psftp -s 2 --description 'Force use of SSH protocol version 2.'
complete -c psftp -s C --description 'Enable SSH compression.'

