# radtest
# Autogenerated from man page /usr/share/man/man1/radtest.1
# using Deroffing man parser
complete -c radtest -s d --description 'The directory that contains the RADIUS dictionary files.'
complete -c radtest -s t --description 'Choose the authentiction method to use.   e. g.'
complete -c radtest -s x --description 'Enables debugging output for the RADIUS client.'
complete -c radtest -s 4 --description 'Use NAS-IP-Address for the NAS address (default).'
complete -c radtest -s 6 --description 'Use NAS-IPv6-Address for the NAS address (default).'

