# radwho
# Autogenerated from man page /usr/share/man/man1/radwho.1
# using Deroffing man parser
complete -c radwho -s c --description 'Shows caller ID (if available) instead of the full name.'
complete -c radwho -o draddb_directory --description 'The directory that contains the RADIUS configuration files.'
complete -c radwho -s f --description 'Behave as the \'fingerd\' daemon - waits for one … [See Man Page]'
complete -c radwho -s i --description 'Shows the session ID instead of the full name.'
complete -c radwho -s n --description 'Normally radwho looks up the username in the sy… [See Man Page]'
complete -c radwho -o Nnas_ip_address --description 'Show only those entries which match the given NAS IP address.'
complete -c radwho -s p --description 'Adds an extra column for the port type - I for … [See Man Page]'
complete -c radwho -o Pnas_port --description 'Show only those entries which match the given NAS port.'
complete -c radwho -s r --description 'Outputs all data in raw format - no headers, no… [See Man Page]'
complete -c radwho -s R --description 'Output all data in RADIUS attribute format.'
complete -c radwho -s s --description 'Show full name.'
complete -c radwho -s S --description 'Hide shell users.'
complete -c radwho -o uuser --description 'Show only those entries which match the given u… [See Man Page]'
complete -c radwho -o Uuser --description 'Show only those entries which match the given u… [See Man Page]'
complete -c radwho -s d --description 'The directory that contains the RADIUS configuration files.'
complete -c radwho -s N --description 'Show only those entries which match the given NAS IP address.'
complete -c radwho -s P --description 'Show only those entries which match the given NAS port.'
complete -c radwho -s u --description 'Show only those entries which match the given u… [See Man Page]'
complete -c radwho -s U --description 'Show only those entries which match the given u… [See Man Page]'
complete -c radwho -s Z --description 'When combined with -R, prints out the contents … [See Man Page]'

