# rename
# Autogenerated from man page /usr/local/share/man/man1/rename.1
# using Type1
complete -c rename -s 0 -l null --description 'When reading file names from \\f(CW\\*(C`STDIN\\*(… [See Man Page]'
complete -c rename -s c -l lower-case --description 'Converts file names to all lower case.'
complete -c rename -s C -l upper-case --description 'Converts file names to all upper case.'
complete -c rename -s e -l expr --description 'The \\f(CW\\*(C`code\\*(C\' argument to this option… [See Man Page]'
complete -c rename -s g -l glob --description 'Glob filename arguments.'
complete -c rename -s f -l force --description 'Rename even when a file with the destination na… [See Man Page]'
complete -c rename -s i -l interactive --description 'Ask the user to confirm every action before it is taken.'
complete -c rename -s k -l backwards -l reverse-order --description 'Process the list of files in reverse order, last file first.'
complete -c rename -s l -l symlink --description 'Create symlinks from the new names to the exist… [See Man Page]'
complete -c rename -s L -l hardlink --description 'Create hard links from the new names to the exi… [See Man Page]'
complete -c rename -s n -l dry-run -l just-print --description 'Show how the files would be renamed, but don\'t … [See Man Page]'
complete -c rename -s s -l subst -l simple --description 'Perform a simple textual substitution of \\f(CW\\… [See Man Page]'
complete -c rename -s v -l verbose --description 'Print additional information about the operatio… [See Man Page]'

