# rmtrash
# Autogenerated from man page /usr/local/share/man/man1/rmtrash.1.gz
# using Deroffing man parser
complete -c rmtrash -s u --description 'an optional argument.'
complete -c rmtrash -s h --description 'displays a small help screen displaying these options.'
complete -c rmtrash -s v --description 'prints out version info on rmtrash.'

