# secutil
# Autogenerated from man page /usr/share/man/man1/secutil.1
# using Deroffing man parser
complete -c secutil -s s -o strongname --description 'Display strongname informations about the assembly.'
complete -c secutil -s x -o x509certificate --description 'Display the X509 Authenticode certificate for the assembly.'
complete -c secutil -s a -o array --description 'Display data in a decimal array (default).'
complete -c secutil -s v -o vbmode --description 'Display data in a VisualBasic friendly format.'
complete -c secutil -s c -o cmode --description 'Display data in a C/C++/C# friendly format (default).'
complete -c secutil -o help -s h -s '?' --description 'Display help about this tool.'

