# setreg
# Autogenerated from man page /usr/share/man/man1/setreg.1
# using Deroffing man parser
complete -c setreg -s q --description 'Quiet mode.  Limited display on console.'
complete -c setreg -o help -s h -s '?' --description 'Display help about this tool.  FEATURES.'

