# sgen
# Autogenerated from man page /usr/share/man/man1/sgen.1
# using Deroffing man parser
complete -c sgen -l 'assembly[:filename]' -s a --description 'Specifies the assembly filename to process.'
complete -c sgen -l 'type[:typefullname]' -s t --description 'Explicitly specifies the runtime type to process.'
complete -c sgen -l 'reference:[filename]' -s r --description 'Specifies an assembly filename, which is refere… [See Man Page]'
complete -c sgen -l 'compiler:[options]' -s c --description 'Specifies compiler options.'
complete -c sgen -l proxytypes -s p --description '(Not supported yet. ).'
complete -c sgen -l debug -s d --description 'Indicates the compiler to generate debug information.'
complete -c sgen -l keep -s k --description 'Indicates the compiler to keep generated tempor… [See Man Page]'
complete -c sgen -l force -s f --description 'Indicates the generator to force overwriting existing assembly.'
complete -c sgen -l 'out:[output-directory]' -s o --description 'Specifies the output directory for resulting files.'
complete -c sgen -l nologo -s n --description 'Indicates to not print the logo for this tool.'
complete -c sgen -l silent -s s --description 'Indicates the tool to run silently.'
complete -c sgen -l verbose -s v --description 'Indicates the tool to be more verbose on its progress.'
complete -c sgen -l help -s '?' --description 'Display command line help.  FEATURES.'

