# signcode
# Autogenerated from man page /usr/share/man/man1/signcode.1
# using Deroffing man parser
complete -c signcode -o spc --description 'The Software Publisher File (spc) that contains the X.'
complete -c signcode -s v --description 'The Private Key File (pvk) that contains the pr… [See Man Page]'
complete -c signcode -s a --description 'The hash algorithm used in the digital signatur… [See Man Page]'
complete -c signcode -s '$' --description 'Add information about the publisher, i. e.'
complete -c signcode -s n --description 'Add a textual description of the signed file.'
complete -c signcode -s i --description 'Add a URL associated to the publisher or the signed file.'
complete -c signcode -s t --description 'URL to a timestamp service to countersign the PE executable.'
complete -c signcode -o tr --description 'Number of retries to get a timestamp for the countersignature.'
complete -c signcode -o tw --description 'Delay (in seconds) between the retries to get a… [See Man Page]'
complete -c signcode -s k --description 'CryptoAPI key container name (when not using -v).'
complete -c signcode -s p --description 'CryptoAPI provider name (when not using -v).'
complete -c signcode -s y --description 'CryptoAPI provider type (when not using -v or -p).'
complete -c signcode -o ky --description 'CryptoAPI key type (when not using -v).'
complete -c signcode -s r --description 'CryptoAPI key location (when not using -v).'
complete -c signcode -o help -s h -s '?' --description 'Display help about this tool.'

