# smbencrypt
# Autogenerated from man page /usr/share/man/man1/smbencrypt.1
# using Deroffing man parser
complete -c smbencrypt -l '------------------------------	--------------------------------' --description '5BFAFBEBFB6A0942AAD3B435B51404EE	AC8E657F83DF82… [See Man Page]'

