# sqlsharp
# Autogenerated from man page /usr/share/man/man1/sqlsharp.1
# using Deroffing man parser
complete -c sqlsharp -s f --description 'Output file to load SQL commands from.'
complete -c sqlsharp -s o --description 'Output file to send results.'
complete -c sqlsharp -s s --description 'Silent mode.'

