# tig
# Autogenerated from man page /usr/local/share/man/man1/tig.1
# using Deroffing man parser
complete -c tig -s v -l version --description 'Show version and exit.'
complete -c tig -s h -l help --description 'Show help message and exit.'

