# tor-gencert
# Autogenerated from man page /usr/local/share/man/man1/tor-gencert.1
# using Deroffing man parser
complete -c tor-gencert -s v --description 'Display verbose output.'
complete -c tor-gencert -s h -l help --description 'Display help text and exit.'
complete -c tor-gencert -s r -l reuse --description 'Generate a new certificate, but not a new signing key.'
complete -c tor-gencert -l create-identity-key --description 'Generate a new identity key.'
complete -c tor-gencert -s i --description 'Read the identity key from the specified file.'
complete -c tor-gencert -s s --description 'Write the signing key to the specified file.  Default: ".'
complete -c tor-gencert -s c --description 'Write the certificate to the specified file.  Default: ".'
complete -c tor-gencert -s m --description 'Number of months that the certificate should be valid.'
complete -c tor-gencert -l passphrase-fd --description 'Filedescriptor to read the file descriptor from.'
complete -c tor-gencert -s a --description 'If provided, advertise the address:port combina… [See Man Page]'

