# tor-resolve
# Autogenerated from man page /usr/local/share/man/man1/tor-resolve.1
# using Deroffing man parser
complete -c tor-resolve -s v --description 'Display verbose output.'
complete -c tor-resolve -s x --description 'Perform a reverse lookup: get the PTR record fo… [See Man Page]'
complete -c tor-resolve -s 5 --description 'Use the SOCKS5 protocol.  (Default).'
complete -c tor-resolve -s 4 --description 'Use the SOCKS4a protocol rather than the defaul… [See Man Page]'

