# tor
# Autogenerated from man page /usr/local/share/man/man1/tor.1
# using Deroffing man parser
complete -c tor -s h -o help --description 'Display a short help message and exit.'
complete -c tor -s f --description 'FILE contains further "option value" pairs.'
complete -c tor -l hash-password --description 'Generates a hashed password for control port access.'
complete -c tor -l list-fingerprint --description 'Generate your keys and output your nickname and fingerprint.'
complete -c tor -l verify-config --description 'Verify the configuration file is valid.'
complete -c tor -l nt-service --description '--service [install|remove|start|stop] Manage th… [See Man Page]'
complete -c tor -l list-torrc-options --description 'List all valid options.'
complete -c tor -l version --description 'Display Tor version and exit.'
complete -c tor -l quiet --description 'Do not start Tor with a console log unless expl… [See Man Page]'
complete -c tor -l service --description 'Manage the Tor Windows NT/2000/XP service.'

