# wifidiagnose
# Autogenerated from man page /usr/share/man/man1/wifidiagnose.1
# using Darwin man parser
complete -c wifidiagnose -o scan --description 'scan for Wi-Fi networks using either an active … [See Man Page]'
complete -c wifidiagnose -o tests --description 'run diagnostics tests either all tests which ca… [See Man Page]'
complete -c wifidiagnose -o monitor --description 'monitor the Wi-Fi link performance, event log, … [See Man Page]'
complete -c wifidiagnose -o time --description 'seconds to monitor performance, events or traffic.'
complete -c wifidiagnose -o browse --description 'browse for and resolve common Bonjour services … [See Man Page]'

